trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- build
- deploy

build:
  stage: build
  displayName: 'Build'
  jobs:
  - job: build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'

deploy:
  stage: deploy
  displayName: 'Deploy'
  jobs:
  - job: deploy
    steps:
    - task: AzureAppServiceDeployment@2
      displayName: 'Deploy to Staging'
      inputs:
        azureSubscription: 'my-azure-subscription'
        appServiceName: 'my-app-service'
        package: '$(System.ArtifactsDirectory)/**/*.zip'
        environmentName: 'staging'