trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Run a script'
  inputs:
    command: 'echo Hello World'

- task: Notify@1
  displayName: 'Send notifications'
  inputs:
    notificationType: 'email'
    emailRecipients: 'user1@example.com,user2@example.com'
    emailSubject: 'Pipeline notification'
    emailBody: 'The pipeline has completed with $(Agent.JobStatus)'

notifications:
  pipelines:
    - pipeline: '*'
      notifications:
        - notification: 'email'
          recipients:
            - 'user1@example.com'
            - 'user2@example.com'
          events:
            - pipelineFailure
            - pipelineSuccess
            - pipelineCancellation